AWSTemplateFormatVersion: 2010-09-09

Description: |
  This template creates a security group that enables SSH and HTTP access.

Resources:
  MySecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enables SSH and HTTP for CFN Instances
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0341d95f75f311023
      InstanceType: t3.micro
      KeyName: first-key
      SecurityGroupIds: 
        - !Ref MySecGrp
      Tags:
        - Key: Name
          Value: ogulcan-cfn-instance
