version: 0.2

phases:
  install:
    commands:
      - node -v
      - npm -v
      - npm install -g @angular/cli@9.0.6

  pre_build:
    commands:
      - npm install

  build:
    commands:
      - ng build --prod

artifacts:
  base-directory: dist
  files:
    - "**/*"
